# PostgreSQL (Docker Compose)
spring.datasource.url=jdbc:postgresql://db:5432/helloworld
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=helloworld
spring.datasource.password=helloworld
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
